import { Product, StoreCategory, Review } from "./types";

export const CATEGORIES: StoreCategory[] = [
  {
    id: "todos",
    name: "Todos",
    description: "Toda a nossa coleção de produtos esportivos de alta performance.",
    icon: "Grid",
  },
  {
    id: "calcados",
    name: "Calçados",
    description: "Tênis esportivos com máxima absorção de impacto, leveza e durabilidade.",
    icon: "Footprints",
  },
  {
    id: "equipamentos",
    name: "Equipamentos",
    description: "Acessórios profissionais para o seu esporte favorito e treinos de alta intensidade.",
    icon: "Dumbbell",
  },
  {
    id: "vestuario",
    name: "Vestuário",
    description: "Roupas leves com tecnologia Dry-Fit e proteção térmica/UV para seu conforto.",
    icon: "Shirt",
  },
  {
    id: "acessorios",
    name: "Acessórios",
    description: "Garrafas térmicas, mochilas esportivas, relógios inteligentes e muito mais.",
    icon: "Compass",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Tênis Elite Runner Pro-X",
    description: "Sinta o máximo amortecimento e propulsão com o novo Elite Runner Pro-X. Desenvolvido para maratonas e treinos de alta intensidade, conta com placa de fibra de carbono integrada, cabedal respirável em malha elástica e sola de aderência superior para asfalto.",
    price: 899.90,
    category: "calcados",
    image: "/src/assets/images/running_shoes_1782419974568.jpg",
    rating: 4.9,
    reviewsCount: 142,
    sizes: ["38", "39", "40", "41", "42", "43"],
    colors: ["Verde Neon", "Preto Carbono", "Azul Elétrico"],
    inStock: true,
    featured: true,
    specs: {
      "Material": "Mesh respirável de alta resistência",
      "Tecnologia": "Placa de Carbono Propulsora",
      "Peso": "210g (Tamanho 40)",
      "Drop": "8mm",
    },
  },
  {
    id: "2",
    name: "Bola de Futebol Golden Match Pro",
    description: "A bola de futebol oficial das grandes partidas. Projetada com selagem térmica de última geração que impede a absorção de água, textura aerodinâmica para trajetórias impecáveis e detalhes metálicos em dourado.",
    price: 249.90,
    category: "equipamentos",
    image: "/src/assets/images/soccer_ball_1782419987367.jpg",
    rating: 4.8,
    reviewsCount: 88,
    inStock: true,
    featured: true,
    specs: {
      "Material": "Poliuretano Termofusionado",
      "Câmara": "Butil para retenção perfeita de ar",
      "Tamanho": "5 (Oficial)",
      "Certificado": "Padrão FIFA Pro Match",
    },
  },
  {
    id: "3",
    name: "Garrafa Térmica Smart Hydrate 900ml",
    description: "Mantenha sua hidratação na temperatura perfeita por até 24 horas fria ou 12 horas quente. Construída em aço inoxidável cirúrgico 18/8 de parede dupla isolada a vácuo, tampa com display LED de temperatura e design ergonômico.",
    price: 159.90,
    category: "acessorios",
    image: "/src/assets/images/water_bottle_1782419999583.jpg",
    rating: 4.7,
    reviewsCount: 215,
    colors: ["Preto Fosco", "Grafite Metálico", "Prata"],
    inStock: true,
    featured: true,
    specs: {
      "Material": "Aço Inoxidável 18/8 livre de BPA",
      "Capacidade": "900 ml",
      "Isolamento": "Parede dupla de vácuo",
      "Bateria Display": "Até 2 anos de autonomia (selada)",
    },
  },
  {
    id: "4",
    name: "Camiseta Dry-Fit Ultra Breathe",
    description: "A camiseta esportiva definitiva para treinos pesados sob o calor. Com tecnologia antissuor de secagem ultrarrápida, costuras planas antiatrito e painéis microperfurados estrategicamente posicionados nas costas.",
    price: 119.90,
    category: "vestuario",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    rating: 4.6,
    reviewsCount: 95,
    sizes: ["P", "M", "G", "GG"],
    colors: ["Cinza Mescla", "Azul Cobalto", "Preto"],
    inStock: true,
    specs: {
      "Material": "100% Poliéster reciclado",
      "Tecnologia": "Dry-Fit AirFlow",
      "Proteção": "FPU 50+ contra raios UV",
      "Corte": "Athletic Fit",
    },
  },
  {
    id: "5",
    name: "Par de Halteres Ajustáveis IronGrip 10kg",
    description: "Otimize o espaço do seu treino em casa. Esse par de halteres oferece troca rápida de peso através de anilhas emborrachadas rosqueáveis seguras, garantindo aderência firme e sem barulho no chão.",
    price: 349.90,
    category: "equipamentos",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=600",
    rating: 4.9,
    reviewsCount: 112,
    inStock: true,
    specs: {
      "Material": "Aço fundido com revestimento em Neoprene",
      "Ajustes": "2.5kg, 5kg, 7.5kg e 10kg por halter",
      "Acompanha": "2 barras, 8 anilhas e 4 presilhas de segurança",
    },
  },
  {
    id: "6",
    name: "Smartwatch Sport Tracker Pro-V",
    description: "Seu parceiro completo de performance. Monitora frequência cardíaca, oxigênio no sangue, sono e 45 modos esportivos com GPS integrado de altíssima precisão. Resistente à água até 50 metros.",
    price: 799.00,
    category: "acessorios",
    image: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=600",
    rating: 4.5,
    reviewsCount: 64,
    colors: ["Preto Obsidian", "Azul Marinho", "Laranja Sport"],
    inStock: true,
    specs: {
      "Tela": "AMOLED HD 1.43 polegadas",
      "Bateria": "Até 10 dias de uso contínuo",
      "Sensores": "GPS/Glonass, Giroscópio, Frequência Cardíaca Bio-Tracker",
      "Resistência": "Certificado 5ATM (Natação)",
    },
  },
  {
    id: "7",
    name: "Shorts de Corrida Sprint Active 2 em 1",
    description: "Desenvolvido com duas camadas: um short de compressão interno ultra macio para evitar assaduras e um short externo de secagem rápida com bolsos ocultos com zíper para celular e chaves.",
    price: 139.90,
    category: "vestuario",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=600",
    rating: 4.7,
    reviewsCount: 76,
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Chumbo/Verde Neon"],
    inStock: true,
    specs: {
      "Camada Interna": "Poliamida com Elastano compressivo",
      "Camada Externa": "Poliéster ultraleve com elastano",
      "Bolsos": "1 bolso para celular, 1 bolso traseiro com zíper",
    },
  },
  {
    id: "8",
    name: "Raquete de Tênis Smash Carbon 300",
    description: "Uma raquete de alto nível técnico produzida inteiramente em grafite de carbono trançado. Proporciona controle absoluto e potência ideal nas rebatidas, com antivibrador embutido no coração da raquete.",
    price: 649.90,
    category: "equipamentos",
    image: "https://images.unsplash.com/photo-1579758629938-03607ccdbaba?q=80&w=600",
    rating: 4.8,
    reviewsCount: 51,
    inStock: false,
    specs: {
      "Material": "100% Fibra de Carbono Premium",
      "Peso": "300g (sem cordas)",
      "Área de Cabeça": "100 sq. in.",
      "Padrão de Cordas": "16x19",
    },
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    user: "Rodrigo Mendonça",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100",
    rating: 5,
    comment: "O Tênis Elite Runner Pro-X superou minhas expectativas! Muito leve e a impulsão da placa de carbono faz muita diferença nos treinos de tiro e provas longas. Entrega super rápida!",
    date: "22 Jun 2026",
  },
  {
    id: "r2",
    user: "Larissa Silva",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    rating: 5,
    comment: "Comprei a Garrafa Térmica e ela realmente segura a água gelada com pedras de gelo o dia inteiro, mesmo no calor de Cuiabá. O sensor de temperatura na tampa funciona perfeitamente.",
    date: "18 Jun 2026",
  },
  {
    id: "r3",
    user: "Marcos Souza",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    rating: 4,
    comment: "A bola de futebol Golden Match Pro tem um toque excelente e voo super estável. Comprei para os jogos de final de semana com os amigos e todos elogiaram. Recomendo muito.",
    date: "15 Jun 2026",
  },
];
